---
- name: "Converge - Preinstall"
  hosts: "all"
  become: true

  vars:
    pip_install_packages:
      - name: "docker"

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: "yes"
      when: "ansible_os_family == 'Debian'"

  roles:
    - "geerlingguy.pip"
    - "geerlingguy.docker"

- name: "Converge"
  hosts: "all"
  become: true

  vars:
    postgres_docker_initscripts:
      - "/opt/pginit/01_create_user_db.sql"
      - "/opt/pginit/02_create_tables.sh"

  pre_tasks:
    - name: "Make directory for initialization scripts"
      ansible.builtin.file:
        path: "/opt/pginit"
        state: "directory"
        owner: "root"
        group: "root"
        mode: "0777"

    - name: "Copy initialization scripts"
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "/opt/pginit/"
        owner: "root"
        group: "root"
        mode: "{{ item.mode }}"
      loop:
        - src: "files/01_create_user_db.sql"
          mode: "0440"
        - src: "files/02_create_tables.sh"
          mode: "0750"

  roles:
    - "organicveggie.postgres_docker"
