---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/resources/requirements.yml
    role-file: molecule/resources/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
  inventory:
    host_vars:
      instance:
        postgres_docker_name: "pgcustom"
        postgres_docker_volume_init_name: "pgcustom-init"
        postgres_docker_volume_conf_name: "pgcustom-conf"
        postgres_docker_volume_data_name: "pgcustom-data"
        postgres_docker_memory: "1GB"
        postgres_docker_cpu: "1"
        postgres_docker_network_create: "true"

verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint .
