---
dependency:
  name: galaxy
  options:
    requirements-file: molecule/resources/requirements.yml
    role-file: molecule/resources/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    converge: ../resources/playbooks/converge.yml
  inventory:
    host_vars:
      instance:
        postgres_docker_memory: "1GB"
        postgres_docker_cpu: "1"
        postgres_docker_use_volumes: "false"

verifier:
  name: ansible
