---
dependency:
  name: "galaxy"
  options:
    requirements-file: "molecule/resources/requirements.yml"
    role-file: "molecule/resources/requirements.yml"

driver:
  name: "${MOLECULE_DRIVER_NAME:-docker}"

platforms:
  - name: "instance"
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2004}-ansible:latest"
    command: "${MOLECULE_DOCKER_COMMAND:-''}"
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    privileged: "true"
    pre_build_image: "true"

  - name: "lxd-instance"
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"

provisioner:
  name: "ansible"
  playbooks:
    converge: "../resources/playbooks/converge.yml"
  inventory:
    group_vars:
      all:
        postgres_docker_memory: "1GB"
        postgres_docker_cpu: "1"
        postgres_docker_use_volumes: "false"

verifier:
  name: "ansible"
