---
dependency:
  name: "galaxy"
  options:
    requirements-file: "requirements.yml"
    role-file: "requirements.yml"

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: "vagrant-instance"
    box: "generic/${MOLECULE_DISTRO:-ubuntu2204}"
    memory: 2048
    cpus: 2

  - name: "lxd-instance"
    url: "${LXD_HOST:-unix:/var/snap/lxd/common/lxd/unix.socket}"
    source:
      alias: "${MOLECULE_DISTRO:-ubuntu/20.04}"

provisioner:
  name: "ansible"
  playbooks:
    converge: "../resources/playbooks/converge.yml"
  inventory:
    group_vars:
      all:
        postgres_docker_memory: "1GB"
        postgres_docker_cpu: "1"
        postgres_docker_use_volumes: "false"

verifier:
  name: "ansible"
