---
- name: "Converge"
  hosts: "all"
  become: true

  vars:
    pip_install_packages:
      - name: "docker"
    docker_daemon_options:
      storage-driver: "overlay2"

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: "yes"
      when: "ansible_os_family == 'Debian'"

  #   - name: "Wait for systemd to complete initialization"
  #     ansible.builtin.command: "systemctl is-system-running"  # noqa: command-instead-of-module
  #     register: "systemctl_status"
  #     until: >
  #       'running' in systemctl_status.stdout or
  #       'degraded' in systemctl_status.stdout
  #     retries: 30
  #     delay: 5
  #     when: "ansible_service_mgr == 'systemd'"
  #     changed_when: "false"
  #     failed_when: "systemctl_status.rc > 1"

  #   - name: "Install timezone data"
  #     ansible.builtin.apt:
  #       name: "tzdata"
  #       state: "present"
  #     when: "ansible_os_family == 'Debian'"

  #   - name: "Set timezone to Asia/Tokyo"
  #     community.general.timezone:
  #       name: "Asia/Tokyo"
  #     when: "ansible_os_family == 'Debian'"

  roles:
    - "geerlingguy.pip"
    - "geerlingguy.docker"
    - "organicveggie.postgres_docker"
