---
- name: "Converge"
  hosts: "all"
  become: true

  vars:
    pip_install_packages:
      - name: "docker"

  pre_tasks:
    - name: "Update apt cache"
      ansible.builtin.apt:
        cache_valid_time: 600
        update_cache: "yes"
      when: "ansible_os_family == 'Debian'"

  roles:
    - "geerlingguy.pip"
    - "geerlingguy.docker"
    - "organicveggie.postgres_docker"
