---
name: "Lint"

on:
  push: null
  pull_request:
    branches:
      - "main"
  workflow_dispatch: null

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v3"

      - name: "Set up Python 3."
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"

      - name: "Install lint dependencies."
        run: "pip3 install yamllint ansible ansible-lint"

      - name: "Install Ansible role requirements"
        run: >
          ansible-galaxy role install --role-file requirements.yml

      - name: "Run linters"
        run: |
          yamllint -c .yamllint -f github -s .
          ansible-lint
