name: Molecule

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - custom_names
          - init_scripts
          - no_volumes
          - traefik
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "organicveggie.postgres_docker"
      - name: Molecule
        uses: gofrolist/molecule-action@v2
        with:
          molecule_options: --debug
          molecule_command: test
          molecule_args: --scenario-name ${{ matrix.scenario }} -d docker
          molecule_working_dir: "organicveggie.postgres_docker"
        env:
          ANSIBLE_FORCE_COLOR: "1"
