name: Molecule

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - custom_names
          - init_scripts
          - no_volumes
          - traefik
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: "organicveggie.postgres_docker"
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install "molecule"
          python3 -m pip install "ansible-lint"
          python3 -m pip install "molecule[docker]"
      - name: Test with molecule
        run: |
          cd organicveggie.postgres_docker
          molecule --debug test --scenario-name ${{ matrix.scenario }} -d docker
