---
name: "Molecule"

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch: null

defaults:
  run:
    working-directory: "organicveggie.postgres_docker"

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v2"
        with:
          path: "organicveggie.postgres_docker"

      - name: "Set up Python 3."
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"

      - name: "Install lint dependencies."
        run: "pip3 install yamllint ansible ansible-lint"

      - name: "Install Ansible role requirements"
        run: >
          ansible-galaxy role install --role-file molecule/resources/requirements.yml
        working-directory: "organicveggie.postgres_docker"

      - name: "Run linters"
        run: |
          yamllint -c .yamllint -f github -s .
          ansible-lint
        working-directory: "organicveggie.postgres_docker"

  molecule:
    name: "Molecule"
    runs-on: "ubuntu-latest"
    strategy:
      fail-fast: false
      matrix:
        distro:
          - "centos/8-Stream/cloud"
          - "debian/bullseye/cloud"
          - "fedora/35/cloud"
          - "ubuntu/20.04/cloud"

    steps:
      - name: "Check out the codebase."
        uses: "actions/checkout@v2"
        with:
          path: "organicveggie.postgres_docker"

      - name: "Set up Python 3."
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.x"

      - name: "Initialize LXD"
        uses: bonddim/action-lxd-init@stable

      - name: "Install tox"
        run: >
          python -m pip install tox

      - name: "Run Molecule tests."
        run: >
          tox -- --debug test --platform-name lxd-instance --driver-name lxd --scenario-name default
        env:
          PY_COLORS: "1"
          ANSIBLE_FORCE_COLOR: "1"
          MOLECULE_DISTRO: "${{ matrix.distro }}"

# yamllint disable rule:comments-indentation
  # molecule:
  #   name: "Molecule"
  #   runs-on: "ubuntu-22.04"
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       distro:
  #         - "centos8"
  #         - "ubuntu2204"
  #         - "ubuntu2004"
  #         - "ubuntu1804"
  #         - "debian11"
  #         - "debian10"
  #         - "fedora34"
  #         - "fedora33"

  #   steps:
  #     - name: "Check out the codebase."
  #       uses: "actions/checkout@v2"
  #       with:
  #         path: "organicveggie.postgres_docker"

  #     - name: "Set up Python 3."
  #       uses: "actions/setup-python@v4"
  #       with:
  #         python-version: "3.x"

  #     - name: "Install tox"
  #       run: >
  #         python -m pip install tox

  #     - name: "Run Molecule tests."
  #       run: "tox -- --debug test"
  #       env:
  #         PY_COLORS: "1"
  #         ANSIBLE_FORCE_COLOR: "1"
  #         MOLECULE_DISTRO: "${{ matrix.distro }}"
# yamllint enable rule:comments-indentation
